name: Deploy App on VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy latest frontend code to real deployment directory
        run: |
          rsync -a --delete --exclude='.env.production' ./ /home/itcweb/frontend/

      - name: Build and deploy with Docker Compose
        run: |
          cd /home/itcweb/
          docker compose down
          docker compose up --build -d
